name: CI - Tests IntelliEditor

on:
  push:
    branches: [ main, dev-A, dev-B, dev-C, dev-D ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installer MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmocka
            mingw-w64-x86_64-pcre2
            mingw-w64-x86_64-cjson
            mingw-w64-x86_64-hunspell
            make
      - name: Compiler et tester
        shell: msys2 {0}
        run: |
          cd $GITHUB_WORKSPACE
          make ENABLE_CJSON=1 ENABLE_PCRE2=1 ENABLE_HUNSPELL=1 test
